### ISSUE TITLE
Improve github actions testing matrix

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/crispy-forms-bootstrap2#1]
Hi @django-crispy-forms/core-team ,

I've been trying this evening to improve the testing matrix but I've been struggling. 
Here is a link to the file [link](https://github.com/django-crispy-forms/crispy-forms-bootstrap2/blob/master/.github/workflows/pythonpackage.yml)

So far I've managed to set up the tests and get them passing. They are running against 2 versions of Django and 3 versions of Python. There is then an exception so that version 3 of Django isn't tested against python 3.5. So far so good. 

The improvements I've been trying to make are: 

- [ ] Give a range of versions for Django (i.e. >=2.2,<2.3, and not 2.2.6)
- [ ] test against master of django-crispy-forms

**Comment by bryan-brancotte** [comment]
Maybe instead of installing from pypi, we could install it directly from the tag repo : 
```
pip install django-crispy-forms==1.8
```

```
pip install git+https://github.com/django-crispy-forms/django-crispy-forms.git@1.8.0
```
I'm trying it with 0364e87

**Comment by bryan-brancotte** [comment]
seems to be working but the workflow is never ending
