### ISSUE TITLE
`templates/` not included in the package

### ISSUE THREAD

**Issue by Situphen** [django-crispy-forms/crispy-forms-bootstrap2#7]
Hi,

I am upgrading one project to `django-crispy-forms` 2.0 and we are still using Bootstrap 2. I followed the Migration Guide : I installed this package, added it to `INSTALLED_APPS`, modified `CRISPY_ALLOWED_TEMPLATE_PACKS` and `CRISPY_TEMPLATE_PACK` but I got this error:

```
django.template.exceptions.TemplateDoesNotExist: bootstrap/field.html
```

I checked the template engine settings and it is looking for `templates/` dirs inside packages dirs.

![image](https://github.com/django-crispy-forms/crispy-forms-bootstrap2/assets/6664636/b5e38888-1a7a-4d12-9a1e-f66e98814ef4)

Then, I checked inside this package dir and `template/` is missing : 

```console
$ ls zdsenv/lib/python3.10/site-packages/crispy_forms_bootstrap2/
__init__.py  __pycache__
```

Whereas it is not missing with `crispy-bootstrap3` : 

```console
$ ls zdsenv/lib/python3.10/site-packages/crispy_bootstrap3
__init__.py  __pycache__  templates
```

I guess there is an issue with the configuration within `setup.py` that leads `templates/` to be missing?

Versions used:
- Python 3.10
- pip 23.2.1
- django-crispy-forms 2.0
- crispy-forms-bootstrap2 2022.1

**Comment by philippemilink** [comment]
Gentle ping about this issue @smithdc1 @bryan-brancotte...

**Comment by bryan-brancotte** [comment]
Hi, you're right template were not included, I proposed some changes to add them in #8

**Comment by smithdc1** [comment]
@philippemilink  -- I've published a new release to PyPI. Can you confirm it works for you? 

https://pypi.org/project/crispy-forms-bootstrap2/2024.1/

**Comment by Situphen** [comment]
Yes, it works fine with this new version, thank you!
